### ISSUE TITLE
Make loggregator go-getable.

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/loggregator-release#331]
There is need to make loggregator go-getable. This issue documents the intended transition.

## Goals:

- Allow loggregator to be go-getable.
- Make loggregator consistent with the rest of the bosh/cloudfoundry ecosystem. The bosh release
  name is currently `logggregator` while it should be `loggregator-release`.
- Do not break older versions of `cf-release`.
  - There are submoduled versions of loggregator in `cf-release`. These submodules point to
    specific SHAs at https://github.com/cloudfoundry/loggregator. These SHAs for older versions
    can not be updated and thus need to continue to work into the future.
- Do not break older versions of `cf-deployment`.
  - `cf-deployment` currently pulls from https://bosh.io/d/github.com/cloudfoundry/loggregator
    These URLs should continue to function for older versions of `cf-deployment`.
- Preserve all github issues and PRs on the bosh release repo.

## Desired End State:

There will be two repositories after this transition:

- loggregator source (no bosh) located at https://github.com/cloudfoundry/loggregator
- loggregator bosh release located at https://github.com/cloudfoundry/loggregator-release

### Phase 1 - The Move:

- [x] Move https://github.com/cloudfoundry/loggregator to https://github.com/cloudfoundry/loggregator-release
  - This will setup a redirect that will allow `cf-release` submodule to continue to function.
- [x] Update `cf-release` submodule to point to https://github.com/cloudfoundry/loggregator-release
- [x] Fix bosh.io:
  - We are not sure if bosh.io will continue to poll the repo for newer final releases. If it does not follow the redirect this will need to be fixed.
  - We will eventually want https://github.com/cloudfoundry/loggregator to be source code only without a redirect so bosh.io will need to:
    - Create a new release for https://github.com/cloudfoundry/loggregator-release
    - Hide https://github.com/cloudfoundry/loggregator and stop pulling from that repo for new releases. This is needed to allow old versions of `cf-deployment` to continue to be able to find releases.
- [x] Update `cf-deployment` to poll from the right bosh.io repo.

### Phase 2 - Extracting Source Code:

- [x] Create a new repo at https://github.com/cloudfoundry/loggregator.
  - This will contain the entire history of the loggregator project, bosh release included.
- [x] Create an orphaned branch on https://github.com/cloudfoundry/loggregator that will be source code only.
- [x] Update https://github.com/cloudfoundry/loggregator-release to submodule https://github.com/cloudfoundry/loggregator
- [x] Update workstation aliases
- [x] Backport any changes missed due to race
- [x] Close all source code PRs that are no longer mergable
- [x] Updates to CI:
  - Add ability to bump the release repo.
  - Make the main pipeline function the same as `statsd-injector-release` and `cf-syslog-drain-release`.

@dsabeti @cppforlife We would appreciate your input on this migration as it involves bosh.io, `cf-deployment`, and `cf-release`. We will be doing it in the next week or so.

**Comment by jvshahid** [comment]
as mentioned in this [slack conversation](https://cloudfoundry.slack.com/archives/C02HCCXV5/p1507561498000227) there is an edge case that isn't explicitly mentioned in this issue. As soon as the new `loggregator` repo is created the github redirects will break. This breaks old `cf-release` since they will be pointing at a sha that doesn't exist. @enocom pointed out that the team is aware of this edge case and are planning to include all the `loggregator-release` commits on a branch in the new `loggregator` repo

**Comment by apoydence** [comment]
@jvshahid Is there a contract for cf-release that we won't break older versions? How long would we have to wait?

**Comment by dsabeti** [comment]
@apoydence There's never been an explicit contract, but we've tried never to break old versions of cf-release. However, since we're going to sunset cf-release soon in favor of cf-deployment, I'd say the deadline for supporting the backwards compatibility would be cf-release's deprecation (2-3 more months from now).

**Comment by jasonkeene** [comment]
@jvshahid @dsabeti @apoydence 

`cf-release` will not be broken. Note in the issue:

> This will contain the entire history of the loggregator project, bosh release included.

This will contain all SHAs that `cf-release` links against.

We will not break `cf-release`.

**Comment by apoydence** [comment]
@jasonkeene Would that imply that we would forever have bosh concerns in the loggregator repo? I would hope at some point we could remove those and decouple ourselves a bit.

**Comment by jasonkeene** [comment]
@apoydence The "bosh concerns" would be isolated to an orphaned branch. It would only be a problem when cloning the repo down since you would get all the objects from the past when "bosh concerns" were a thing.  Luckily git is pretty good at packing objects into `.pack` files so it isn't a big cost.

**Comment by jasonkeene** [comment]
PR to update bosh.io to use the new repo URL: https://github.com/bosh-io/releases/pull/20

**Comment by jasonkeene** [comment]
PR for cf-deployment to use the new bosh.io URL: https://github.com/cloudfoundry/runtime-ci/pull/18

**Comment by enocom** [comment]
Done! Closing.
